-- Função para atualizar o timestamp automaticamente
create or replace function atualizar_timestamp()
returns trigger as $$
begin
    new.updated_at = timezone('utc'::text, now());
    return new;
end;
$$ language plpgsql;

-- ==============================
-- Tabela: alunos
-- ==============================
create table alunos (
    id bigint generated by default as identity primary key,
    encryption_key text unique not null,
    password text not null,
    created_at timestamptz default timezone('utc'::text, now()) not null,
    updated_at timestamptz default timezone('utc'::text, now()) not null,
    name text not null,
    photo_url text,
    birthdate date not null,
    cpf text unique not null,
    email text unique not null,
    class Text not null
);

create trigger trg_atualiza_aluno
before update on alunos
for each row
execute function atualizar_timestamp();

-- ==============================
-- Tabela: alunos_tokens
-- ==============================
create table alunos_tokens (
    id bigint generated by default as identity primary key,
    aluno_id bigint not null,
    created_at timestamptz default timezone('utc'::text, now()) not null,
    updated_at timestamptz default timezone('utc'::text, now()) not null,
    token text unique not null,
    constraint fk_alunos_tokens_aluno
        foreign key (aluno_id) references alunos (id) on delete cascade
);

create index idx_alunos_tokens_aluno_id
on alunos_tokens (aluno_id);

create trigger trg_atualiza_aluno_token
before update on alunos_tokens
for each row
execute function atualizar_timestamp();

-- ==============================
-- Tabela: professores
-- ==============================
create table professores (
    id bigint generated by default as identity primary key,
    encryption_key text unique not null,
    password text not null,
    created_at timestamptz default timezone('utc'::text, now()) not null,
    updated_at timestamptz default timezone('utc'::text, now()) not null,
    name text not null,
    photo_url text,
    birthdate date not null,
    cpf text unique not null,
    email text unique not null
);

create trigger trg_atualiza_professor
before update on professores
for each row
execute function atualizar_timestamp();

-- ==============================
-- Tabela: professores_tokens
-- ==============================
create table professores_tokens (
    id bigint generated by default as identity primary key,
    professor_id bigint not null,
    created_at timestamptz default timezone('utc'::text, now()) not null,
    updated_at timestamptz default timezone('utc'::text, now()) not null,
    token text unique not null,
    constraint fk_professores_tokens_professor
        foreign key (professor_id) references professores (id) on delete cascade
);

create index idx_professores_tokens_professor_id
on professores_tokens (professor_id);

create trigger trg_atualiza_professor_token
before update on professores_tokens
for each row
execute function atualizar_timestamp();

-- ==============================
-- Tabela: perfis
-- ==============================
create table perfis (
    id bigint generated by default as identity primary key,
    aluno_id bigint not null,
    created_at timestamptz default timezone('utc'::text, now()) not null,
    updated_at timestamptz default timezone('utc'::text, now()) not null,
    skills text,
    experiences text,
    contact text,
    constraint fk_perfis_aluno
        foreign key (aluno_id) references alunos (id) on delete cascade
);

create trigger trg_atualiza_perfil
before update on perfis
for each row
execute function atualizar_timestamp();

-- ==============================
-- Tabela: projetos
-- ==============================
create table projetos (
    id bigint generated by default as identity primary key,
    professor_id bigint not null,
    created_at timestamptz default timezone('utc'::text, now()) not null,
    updated_at timestamptz default timezone('utc'::text, now()) not null,
    requirements text,
    description text,
    contact text,
    vacancies int not null,
    constraint fk_projetos_professor
        foreign key (professor_id) references professores (id) on delete cascade
);

create trigger trg_atualiza_projeto
before update on projetos
for each row
execute function atualizar_timestamp();
